# Generated by Django 2.0 on 2020-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200430_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('Red', 'Red')], default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='3', max_length=20),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
