# Generated by Django 2.0 on 2020-05-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.Product'),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
