# Generated by Django 2.0 on 2020-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200502_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='title',
            new_name='color',
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
