# Generated by Django 2.0 on 2020-05-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200502_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image1', to='store.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='variationcolor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variationcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variationsize',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variationsize',
            name='product',
        ),
        migrations.DeleteModel(
            name='VariationColor',
        ),
        migrations.DeleteModel(
            name='VariationSize',
        ),
    ]
