# Generated by Django 2.0 on 2020-05-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200502_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('Red', 'Red')], default='Blue', max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='L', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
