# Generated by Django 2.0 on 2020-05-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200502_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='colorSize',
        ),
    ]
